name: Build Chapter-Plugin

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
    - name: Deploy to Live Environment
      uses: actions/upload-artifact@v2
      with:
        name: live-js
        path: pubilc/*.js 
